### ISSUE TITLE
navでwidthが770pxだとdisplay:noneがspでもpcでも有効になる

### ISSUE THREAD

**Issue by bmf-san** [bmf-san/sea.css#46]
min-width669pxとmax-width770pxのように1pxずらす必要がある。770pxのときpcでもspでもdisplay  noneとなってしまう。

```css
@media screen and (min-width: 770px) {
  .pc-hidden {
    display: none;
  }
}

@media screen and (max-width: 770px) {
  .sp-hidden {
    display: none;
  }
```
